[package]
name = "rs-consul"
version = "0.2.0"
authors = ["Roblox"]
edition = "2018"
description = "This crate provides access to a set of strongly typed apis to interact with consul (https://www.consul.io/)"
readme = "README.md"
repository = "https://github.com/Roblox/rs-consul"
license = "MIT"
license-file = "LICENSE"

[features]
default = ["native-tls"]
native-tls = ["hyper-tls"]
rustls-tls = ["hyper-rustls"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# keep this list sorted!
[dependencies]
base64 = "0.13.0"
futures = "0.3.8"
http = "0.2.1"
hyper = { version = "0.14.2", features = ["full"] }
hyper-tls = { version = "0.5.0", optional = true }
hyper-rustls = { version = "0.22", optional = true }
opentelemetry = { version = "0.16", features = ["tokio", "rt-tokio"] }
quick-error = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog-scope = "4.3"
smart-default = "0.6.0"
tokio = { version = "1.1", features = ["full"] }
ureq = { version = "2.2", features = ["json"] }

[dev-dependencies]
base64 = "0.13.0"
